name: CI/CD Workflow

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change this to your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Package
        run: npm run build # Change this to your build command if needed

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only publish from the main branch

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change this to your desired Node.js version

      - name: Login to npm
        run: npm login --registry=https://registry.npmjs.org/ --scope=@pappijx --always-auth # Replace @your-scope with your npm scope

      - name: Publish Package
        run: npm publish --access public # Use "--access public" if your package is meant to be public, remove it otherwise
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # Ensure you have NPM_TOKEN added as a secret in your repository settings

